apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: ory
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: registry-jpe.ubitus.net/library/qy-echo-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: ory
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500
